// <auto-generated />
using DraftSQliteDb.WebApi;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DraftSQliteDb.WebApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250418195018_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("DraftSQliteDb.WebApi.Model.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AddressCity")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("TEXT")
                        .HasComputedColumnSql("json_extract(Contact, '$.Address.City')", true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AddressCity")
                        .HasDatabaseName("IX_Authors_AddressCity");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("DraftSQliteDb.WebApi.Model.Author", b =>
                {
                    b.OwnsOne("DraftSQliteDb.WebApi.Model.Contact", "Contact", b1 =>
                        {
                            b1.Property<int>("AuthorId")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Phone")
                                .HasColumnType("TEXT");

                            b1.HasKey("AuthorId");

                            b1.ToTable("Authors");

                            b1.ToJson("Contact");

                            b1.WithOwner()
                                .HasForeignKey("AuthorId");

                            b1.OwnsOne("DraftSQliteDb.WebApi.Model.Address", "Address", b2 =>
                                {
                                    b2.Property<int>("ContactAuthorId")
                                        .HasColumnType("INTEGER");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Postcode")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("TEXT");

                                    b2.HasKey("ContactAuthorId");

                                    b2.ToTable("Authors");

                                    b2.WithOwner()
                                        .HasForeignKey("ContactAuthorId");
                                });

                            b1.Navigation("Address")
                                .IsRequired();
                        });

                    b.Navigation("Contact")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
